### ISSUE TITLE
Encountering numpy warnings

### ISSUE THREAD

**Issue by tansudaylan** [stephenportillo/lion#1]
/n/home15/tansu/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/n/home15/tansu/.local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

**Comment by joshspeagle** [comment]
Is there a traceback higher up? This appears like quite an obscure error.

**Comment by tansudaylan** [comment]
Indeed. I updated numpy and it went away!
